# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

git:
  ignore_tags:
    - "v[0-9]*.[0-9]*.[0-9]"
    - "solparq-v*"

builds:
  - id: solparq
    builder: rust
    command: zigbuild
    binary: solparq
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
    flags:
      - --release
      - --locked
      - --package=solparq
      - --bin=solparq
    env:
      - SUPERBANK_GIT_SHA={{ .Commit }}
  - id: solparq-read
    builder: rust
    command: zigbuild
    binary: solparq-read
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
    flags:
      - --release
      - --locked
      - --package=solparq-read
      - --bin=solparq-read
    env:
      - SUPERBANK_GIT_SHA={{ .Commit }}

archives:
  - id: solparq
    ids: [solparq]
    name_template: solparq-{{ trimsuffix .Tag "-solparq" }}-{{ .Os }}-{{ .Arch }}
    formats: [tar.gz]
    files: []
  - id: solparq-read
    ids: [solparq-read]
    name_template: solparq-read-{{ trimsuffix .Tag "-solparq" }}-{{ .Os }}-{{ .Arch }}
    formats: [tar.gz]
    files: []

checksum:
  name_template: solparq-{{ trimsuffix .Tag "-solparq" }}-SHA256SUMS.txt

release:
  name_template: 'Solparq {{ trimsuffix .Tag "-solparq" }}'
  header: |
    rust {{ .Env.RUST_VERSION }}

changelog:
  sort: asc
  use: github
