[package]
name = "superbank-workspace"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[workspace.package]
version = "0.6.0-rc1"
edition = "2024"
license = "AGPL-3.0-only"
authors = [
    "Triton One Limited",
    "Miles 'wedtm' Smith <52319902+notwedtm@users.noreply.github.com>",
    "Daniel Camargo <67828229+dancamarg0@users.noreply.github.com>",
    "Augustin Cheron <1165445+augustin-cheron@users.noreply.github.com>",
    "Henry Adenuga <39364502+Mctursh@users.noreply.github.com>",
    "Rishav <68805388+rishavmehra@users.noreply.github.com>",
    "TechieGhost <116256043+gamandeepsingh@users.noreply.github.com>",
    "aspnxdd <43625217+aspnxdd@users.noreply.github.com>",
]

# Versions and baseline features shared by workspace members.
[workspace.dependencies]
anyhow = "1.0"
axum = "0.8"
clap = { version = "4.5.40", features = ["derive", "env"] }
kubert-prometheus-process = "0.2.3"
object_store = { version = "0.13", features = ["aws"] }
prometheus-client = "0.23.1"
prometheus-client-derive-encode = "0.4.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.46.1", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[workspace]
members = [
    "crates/superbank",
    "crates/superbank-rpc",
    "crates/superbank-solparq",
    "crates/superbank-verify",
]

resolver = "2"
default-members = [
    "crates/superbank",
    "crates/superbank-rpc",
    "crates/superbank-solparq",
    "crates/superbank-verify",
]
