-- SPDX-License-Identifier: AGPL-3.0-only
--
-- Copyright 2025-2026 Triton One Limited. All rights reserved.
--

-- Source-of-truth Solana transactions with replicated shard-local storage (raw fidelity for getTransaction).
CREATE TABLE IF NOT EXISTS default.transactions_local ON CLUSTER '{cluster}'
(
    signature         FixedString(64),
    slot              UInt64 CODEC(Delta, ZSTD(1)),
    slot_idx          UInt32 CODEC(Delta, ZSTD(1)),
    block_time        Nullable(Int64) CODEC(Delta, ZSTD(1)),
    message_hash      FixedString(32),
    is_vote           UInt8,
    tx_version                         Nullable(UInt8),
    tx_signatures                      Array(FixedString(64)),
    tx_num_required_signatures         UInt8,
    tx_num_readonly_signed_accounts    UInt8,
    tx_num_readonly_unsigned_accounts  UInt8,
    tx_account_keys                    Array(FixedString(32)),
    tx_recent_blockhash                FixedString(32),
    tx_instructions_program_id_index   Array(UInt8),
    tx_instructions_accounts           Array(Array(UInt8)),
    tx_instructions_data               Array(String) CODEC(ZSTD(3)),
    tx_address_table_lookups_present   UInt8,
    tx_address_table_lookup_account_key        Array(FixedString(32)),
    tx_address_table_lookup_writable_indexes   Array(Array(UInt8)),
    tx_address_table_lookup_readonly_indexes   Array(Array(UInt8)),
    meta_status_ok                     UInt8,
    meta_err                           Nullable(String) CODEC(ZSTD(1)),
    meta_fee                           UInt64 CODEC(ZSTD(1)),
    meta_pre_balances                  Array(UInt64) CODEC(ZSTD(1)),
    meta_post_balances                 Array(UInt64) CODEC(ZSTD(1)),
    meta_inner_instructions_present    UInt8,
    meta_inner_instructions_index              Array(UInt8),
    meta_inner_instructions_program_id_index   Array(Array(UInt8)),
    meta_inner_instructions_accounts           Array(Array(Array(UInt8))),
    meta_inner_instructions_data               Array(Array(String)) CODEC(ZSTD(3)),
    meta_inner_instructions_stack_height       Array(Array(Nullable(UInt32))),
    meta_log_messages_present          UInt8,
    meta_log_messages                  Array(String) CODEC(ZSTD(1)),
    meta_pre_token_balances_present    UInt8,
    meta_pre_token_account_index       Array(UInt8),
    meta_pre_token_mint                Array(FixedString(32)) CODEC(ZSTD(1)),
    meta_pre_token_owner               Array(Nullable(FixedString(32))) CODEC(ZSTD(1)),
    meta_pre_token_program_id          Array(Nullable(FixedString(32))) CODEC(ZSTD(1)),
    meta_pre_token_amount              Array(String) CODEC(ZSTD(1)),
    meta_pre_token_decimals            Array(UInt8),
    meta_pre_token_ui_amount           Array(Nullable(Float64)),
    meta_pre_token_ui_amount_string    Array(String) CODEC(ZSTD(1)),
    meta_post_token_balances_present   UInt8,
    meta_post_token_account_index      Array(UInt8),
    meta_post_token_mint               Array(FixedString(32)) CODEC(ZSTD(1)),
    meta_post_token_owner              Array(Nullable(FixedString(32))) CODEC(ZSTD(1)),
    meta_post_token_program_id         Array(Nullable(FixedString(32))) CODEC(ZSTD(1)),
    meta_post_token_amount             Array(String) CODEC(ZSTD(1)),
    meta_post_token_decimals           Array(UInt8),
    meta_post_token_ui_amount          Array(Nullable(Float64)),
    meta_post_token_ui_amount_string   Array(String) CODEC(ZSTD(1)),
    meta_rewards_present               UInt8,
    meta_reward_pubkey                 Array(String) CODEC(ZSTD(1)),
    meta_reward_lamports               Array(Int64) CODEC(ZSTD(1)),
    meta_reward_post_balance           Array(UInt64) CODEC(ZSTD(1)),
    meta_reward_type                   Array(Nullable(String)) CODEC(ZSTD(1)),
    meta_reward_commission             Array(Nullable(UInt8)),
    meta_reward_commission_bps         Array(Nullable(UInt16)),
    meta_loaded_addresses_writable     Array(FixedString(32)),
    meta_loaded_addresses_readonly     Array(FixedString(32)),
    meta_return_data_present           UInt8,
    meta_return_data_program_id        Nullable(FixedString(32)),
    meta_return_data_data              Nullable(String) CODEC(ZSTD(3)),
    meta_compute_units_consumed        Nullable(UInt64),
    meta_cost_units                    Nullable(UInt64),
    INDEX bf_signature signature TYPE bloom_filter(0.01) GRANULARITY 64
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{cluster}/{database}/{table}/{shard}', '{replica}', slot)
PARTITION BY intDiv(slot, 432000) -- Solana epoch (432k slots)
ORDER BY (slot, slot_idx, signature);

CREATE TABLE IF NOT EXISTS default.transactions ON CLUSTER '{cluster}'
(
    signature         FixedString(64),
    slot              UInt64 CODEC(Delta, ZSTD(1)),
    slot_idx          UInt32 CODEC(Delta, ZSTD(1)),
    block_time        Nullable(Int64) CODEC(Delta, ZSTD(1)),
    message_hash      FixedString(32),
    is_vote           UInt8,
    tx_version                         Nullable(UInt8),
    tx_signatures                      Array(FixedString(64)),
    tx_num_required_signatures         UInt8,
    tx_num_readonly_signed_accounts    UInt8,
    tx_num_readonly_unsigned_accounts  UInt8,
    tx_account_keys                    Array(FixedString(32)),
    tx_recent_blockhash                FixedString(32),
    tx_instructions_program_id_index   Array(UInt8),
    tx_instructions_accounts           Array(Array(UInt8)),
    tx_instructions_data               Array(String) CODEC(ZSTD(3)),
    tx_address_table_lookups_present   UInt8,
    tx_address_table_lookup_account_key        Array(FixedString(32)),
    tx_address_table_lookup_writable_indexes   Array(Array(UInt8)),
    tx_address_table_lookup_readonly_indexes   Array(Array(UInt8)),
    meta_status_ok                     UInt8,
    meta_err                           Nullable(String) CODEC(ZSTD(1)),
    meta_fee                           UInt64 CODEC(ZSTD(1)),
    meta_pre_balances                  Array(UInt64) CODEC(ZSTD(1)),
    meta_post_balances                 Array(UInt64) CODEC(ZSTD(1)),
    meta_inner_instructions_present    UInt8,
    meta_inner_instructions_index              Array(UInt8),
    meta_inner_instructions_program_id_index   Array(Array(UInt8)),
    meta_inner_instructions_accounts           Array(Array(Array(UInt8))),
    meta_inner_instructions_data               Array(Array(String)) CODEC(ZSTD(3)),
    meta_inner_instructions_stack_height       Array(Array(Nullable(UInt32))),
    meta_log_messages_present          UInt8,
    meta_log_messages                  Array(String) CODEC(ZSTD(1)),
    meta_pre_token_balances_present    UInt8,
    meta_pre_token_account_index       Array(UInt8),
    meta_pre_token_mint                Array(FixedString(32)) CODEC(ZSTD(1)),
    meta_pre_token_owner               Array(Nullable(FixedString(32))) CODEC(ZSTD(1)),
    meta_pre_token_program_id          Array(Nullable(FixedString(32))) CODEC(ZSTD(1)),
    meta_pre_token_amount              Array(String) CODEC(ZSTD(1)),
    meta_pre_token_decimals            Array(UInt8),
    meta_pre_token_ui_amount           Array(Nullable(Float64)),
    meta_pre_token_ui_amount_string    Array(String) CODEC(ZSTD(1)),
    meta_post_token_balances_present   UInt8,
    meta_post_token_account_index      Array(UInt8),
    meta_post_token_mint               Array(FixedString(32)) CODEC(ZSTD(1)),
    meta_post_token_owner              Array(Nullable(FixedString(32))) CODEC(ZSTD(1)),
    meta_post_token_program_id         Array(Nullable(FixedString(32))) CODEC(ZSTD(1)),
    meta_post_token_amount             Array(String) CODEC(ZSTD(1)),
    meta_post_token_decimals           Array(UInt8),
    meta_post_token_ui_amount          Array(Nullable(Float64)),
    meta_post_token_ui_amount_string   Array(String) CODEC(ZSTD(1)),
    meta_rewards_present               UInt8,
    meta_reward_pubkey                 Array(String) CODEC(ZSTD(1)),
    meta_reward_lamports               Array(Int64) CODEC(ZSTD(1)),
    meta_reward_post_balance           Array(UInt64) CODEC(ZSTD(1)),
    meta_reward_type                   Array(Nullable(String)) CODEC(ZSTD(1)),
    meta_reward_commission             Array(Nullable(UInt8)),
    meta_reward_commission_bps         Array(Nullable(UInt16)),
    meta_loaded_addresses_writable     Array(FixedString(32)),
    meta_loaded_addresses_readonly     Array(FixedString(32)),
    meta_return_data_present           UInt8,
    meta_return_data_program_id        Nullable(FixedString(32)),
    meta_return_data_data              Nullable(String) CODEC(ZSTD(3)),
    meta_compute_units_consumed        Nullable(UInt64),
    meta_cost_units                    Nullable(UInt64)
)
ENGINE = Distributed('{cluster}', 'default', 'transactions_local', intDiv(slot, 432000));

ALTER TABLE default.transactions_local ON CLUSTER '{cluster}'
    ADD COLUMN IF NOT EXISTS meta_reward_commission_bps Array(Nullable(UInt16)) AFTER meta_reward_commission;
ALTER TABLE default.transactions ON CLUSTER '{cluster}'
    ADD COLUMN IF NOT EXISTS meta_reward_commission_bps Array(Nullable(UInt16)) AFTER meta_reward_commission;
