-- SPDX-License-Identifier: AGPL-3.0-only

-- 1:1 readable projection of default.transactions: same rows (votes
-- included), same structure, with binary keys re-encoded to base58 and
-- block_time as DateTime. Intended for inspecting individual transactions;
-- for analytics prefer the reshaped views (tx_summary, sol_transfers,
-- token_transfers), which also merge ALT-loaded accounts and drop votes.
--
-- Instruction payloads (tx_instructions_data, inner instruction data,
-- meta_return_data_data) are hex-encoded: they are program-specific binary
-- with no generic decoding, but hex keeps them printable and copyable for
-- external decoders.
CREATE VIEW IF NOT EXISTS default.transactions_decoded AS
SELECT
    base58Encode(signature) AS signature,
    slot,
    slot_idx,
    fromUnixTimestamp(block_time) AS block_time,
    base58Encode(message_hash) AS message_hash,
    is_vote,
    tx_version,
    arrayMap(s -> base58Encode(s), tx_signatures) AS tx_signatures,
    tx_num_required_signatures,
    tx_num_readonly_signed_accounts,
    tx_num_readonly_unsigned_accounts,
    arrayMap(k -> base58Encode(k), tx_account_keys) AS tx_account_keys,
    base58Encode(tx_recent_blockhash) AS tx_recent_blockhash,
    tx_instructions_program_id_index,
    tx_instructions_accounts,
    arrayMap(d -> hex(d), tx_instructions_data) AS tx_instructions_data,
    tx_address_table_lookups_present,
    arrayMap(k -> base58Encode(k), tx_address_table_lookup_account_key) AS tx_address_table_lookup_account_key,
    tx_address_table_lookup_writable_indexes,
    tx_address_table_lookup_readonly_indexes,
    meta_status_ok,
    meta_err,
    meta_fee,
    meta_pre_balances,
    meta_post_balances,
    meta_inner_instructions_present,
    meta_inner_instructions_index,
    meta_inner_instructions_program_id_index,
    meta_inner_instructions_accounts,
    arrayMap(inner -> arrayMap(d -> hex(d), inner), meta_inner_instructions_data) AS meta_inner_instructions_data,
    meta_inner_instructions_stack_height,
    meta_log_messages_present,
    meta_log_messages,
    meta_pre_token_balances_present,
    meta_pre_token_account_index,
    arrayMap(k -> base58Encode(k), meta_pre_token_mint) AS meta_pre_token_mint,
    arrayMap(k -> if(k IS NULL, NULL, base58Encode(assumeNotNull(k))), meta_pre_token_owner) AS meta_pre_token_owner,
    arrayMap(k -> if(k IS NULL, NULL, base58Encode(assumeNotNull(k))), meta_pre_token_program_id) AS meta_pre_token_program_id,
    meta_pre_token_amount,
    meta_pre_token_decimals,
    meta_pre_token_ui_amount,
    meta_pre_token_ui_amount_string,
    meta_post_token_balances_present,
    meta_post_token_account_index,
    arrayMap(k -> base58Encode(k), meta_post_token_mint) AS meta_post_token_mint,
    arrayMap(k -> if(k IS NULL, NULL, base58Encode(assumeNotNull(k))), meta_post_token_owner) AS meta_post_token_owner,
    arrayMap(k -> if(k IS NULL, NULL, base58Encode(assumeNotNull(k))), meta_post_token_program_id) AS meta_post_token_program_id,
    meta_post_token_amount,
    meta_post_token_decimals,
    meta_post_token_ui_amount,
    meta_post_token_ui_amount_string,
    meta_rewards_present,
    meta_reward_pubkey,
    meta_reward_lamports,
    meta_reward_post_balance,
    meta_reward_type,
    meta_reward_commission,
    arrayMap(k -> base58Encode(k), meta_loaded_addresses_writable) AS meta_loaded_addresses_writable,
    arrayMap(k -> base58Encode(k), meta_loaded_addresses_readonly) AS meta_loaded_addresses_readonly,
    meta_return_data_present,
    if(meta_return_data_program_id IS NULL, NULL, base58Encode(assumeNotNull(meta_return_data_program_id))) AS meta_return_data_program_id,
    if(meta_return_data_data IS NULL, NULL, hex(assumeNotNull(meta_return_data_data))) AS meta_return_data_data,
    meta_compute_units_consumed,
    meta_cost_units
FROM default.transactions;
