[package]
name = "superbank-verify"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
bs58 = "0.5"
clap.workspace = true
clickhouse = { version = "0.14" }
kubert-prometheus-process.workspace = true
once_cell = "1.21.3"
prometheus-client.workspace = true
prometheus-client-derive-encode.workspace = true
rayon = "1.10"
serde.workspace = true
serde-big-array = "0.5"
serde_json.workspace = true
serde_yaml = "0.9"
sha2 = "0.10"
solana-epoch-schedule = "3.0.0"
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
solana-entry = { version = "3.0.0", features = ["agave-unstable-api"] }
solana-hash = "3.1.0"
solana-merkle-tree = "3.0.0"
solana-message = "3.1.0"
solana-signature = "3.4.0"
solana-transaction = { version = "3.1.0", features = ["serde"] }
tempfile = "3"
