name: GoReleaser config check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - .goreleaser.yaml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  goreleaser-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@1a80836c5c9d9e5755a25cb59ec6f45a3b5f41a8 # v7.2.1
        with:
          version: "~> v2"
          install-only: true

      - name: Check config
        run: goreleaser check --config .goreleaser.yaml
